### PR TITLE
SOMEF-639: Replace hardcoded config paths

### LINKED ISSUE #639: Hardcoded config paths may lead to problems in Windows
In https://github.com/KnowledgeCaptureAndDiscovery/somef/blob/master/src/somef/configuration.py
We have:
```
default_description = str(path) + "/models/description.p"
default_invocation = str(path) + "/models/invocation.p"
default_installation = str(path) + "/models/installation.p"
default_citation = str(path) + "/models/citation.p"
```
@StankovskiA was having issues in his local system (Windows) when installing soca. We should change this to proper paths with path separators

### PR DESCRIPTION
**Pull request by StankovskiA**
<h3> Fixes #639 </h3>
____

This PR simply replaces the string concatenation method of path crafting with the better suited os.path.join() method which ensures correct path strings.

### CODE REVIEW

**Comment by dgarijo** [comment]
Looking good! Please push to the `dev` branch

**Review by dgarijo — CHANGES_REQUESTED** [review]
Please push to the `dev` branch

**Comment by StankovskiA** [comment]
@dgarijo `master` is 4 commits ahead of `dev`. Ideally, that shouldn't be the case and `dev` should be ahead. When I switched the base branch to dev it automatically added the commits that were missing in `dev`. 

We could merge this PR to add the missing commits to `dev` and also the newest commit

**Review by dgarijo — APPROVED** [review]

**Comment by dgarijo** [comment]
What may have happened is that I accepted PRs from dependabot on tests which don't really affect the application. Now both branches should be in sync

**Pull request merged**
